import { DataSource } from 'typeorm';
import {
  AppNotification,
  AgentCreditPayment,
  AuditEvent,
  DailyClose,
  Collection,
  DevicePushToken,
  FawryDailyDrop,
  FawryDeposit,
  FinancialAccount,
  IdempotencyRecord,
  InventoryProduct,
  InventorySale,
  InventoryStockMovement,
  InventoryTreasury,
  LedgerEntry,
  Machine,
  PurchaseVisa,
  RefreshToken,
  Treasury,
  User,
  Wallet,
} from './entities/index.js';

const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST ?? 'localhost',
  port: Number(process.env.DB_PORT ?? 5432),
  username: process.env.DB_USER ?? 'hesba',
  password: process.env.DB_PASSWORD ?? '',
  database: process.env.DB_NAME ?? 'hesba',
  entities: [
    User,
    AgentCreditPayment,
    FawryDailyDrop,
    FawryDeposit,
    FinancialAccount,
    Wallet,
    Machine,
    PurchaseVisa,
    Treasury,
    Collection,
    LedgerEntry,
    AppNotification,
    DevicePushToken,
    InventoryProduct,
    InventorySale,
    InventoryTreasury,
    IdempotencyRecord,
    AuditEvent,
    DailyClose,
    InventoryStockMovement,
    RefreshToken,
  ],
  migrations: [`${import.meta.dirname}/migrations/*.js`],
  migrationsTableName: 'schema_migrations',
  migrationsTransactionMode: 'all',
  synchronize: false,
});

export default AppDataSource;
