// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyTnpBfcwdtjhhcPcdAeewxRF0nBUl5Ao',
    appId: '1:253651325465:web:5a9bd87178cbed92739088',
    messagingSenderId: '253651325465',
    projectId: 'hespa-system',
    authDomain: 'hespa-system.firebaseapp.com',
    storageBucket: 'hespa-system.firebasestorage.app',
    measurementId: 'G-MDRYY4DCQT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3kuh4KD_rA6AhBXzLAU2zee3VUTsgWMA',
    appId: '1:253651325465:ios:ed09dad60c649bef739088',
    messagingSenderId: '253651325465',
    projectId: 'hespa-system',
    storageBucket: 'hespa-system.firebasestorage.app',
    iosBundleId: 'com.hesba.hesbaDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyTnpBfcwdtjhhcPcdAeewxRF0nBUl5Ao',
    appId: '1:253651325465:web:33f8b66187f78a75739088',
    messagingSenderId: '253651325465',
    projectId: 'hespa-system',
    authDomain: 'hespa-system.firebaseapp.com',
    storageBucket: 'hespa-system.firebasestorage.app',
    measurementId: 'G-W3VE76TD64',
  );
}
